language: node_js
warnings_are_errors: false
node_js:
  - "node"
cache:
  - yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: jenyaberlin-kurwid-19-staging
    region: eu-central-1
    acl: public_read
    on:
      branch: develop
  - provider: s3
    warnings_are_errors: false
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: jenyaberlin-kurwid-19-production
    region: eu-central-1
    acl: public_read
    on:
      branch: master
